# Server Configuration
server.port=8080

# Application Configuration
spring.application.name=matching-engine

# Logging Configuration
logging.level.org.example.matching=DEBUG
logging.level.org.springframework.web=INFO

# ---- NEON POSTGRES ----
spring.datasource.url=jdbc:postgresql://ep-odd-hill-anelxy78-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_w16cKfmkSrMj
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- JPA / HIBERNATE ----
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true